name: chat_app_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  firebase_core: ^2.27.1
  cloud_firestore: ^4.15.9
  firebase_auth: ^4.17.9

flutter:
  uses-material-design: true
